on:
  push:
    paths:
      - "package/shared/**"
    branches:
      - master
name: ğŸš€ Publish package on push
jobs:
  package-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          
      - name: NPM Install
        run: |
          cd ./package/api-client
          npm install

      - name: ğŸ”¨ Build Project && Publish
        run: |
          CI=false npm run publish
